//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hbulens.Exam70487.Wcf.Client.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://github.com/hbulens/Exam70487", ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/hbulens/Exam70487/ICustomerService/Get", ReplyAction="https://github.com/hbulens/Exam70487/ICustomerService/GetResponse")]
        hbulens.Exam70487.Common.Customer[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/hbulens/Exam70487/ICustomerService/Get", ReplyAction="https://github.com/hbulens/Exam70487/ICustomerService/GetResponse")]
        System.Threading.Tasks.Task<hbulens.Exam70487.Common.Customer[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/hbulens/Exam70487/ICustomerService/Add", ReplyAction="https://github.com/hbulens/Exam70487/ICustomerService/AddResponse")]
        bool Add(hbulens.Exam70487.Common.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/hbulens/Exam70487/ICustomerService/Add", ReplyAction="https://github.com/hbulens/Exam70487/ICustomerService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(hbulens.Exam70487.Common.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://github.com/hbulens/Exam70487/ICustomerService/SaveChanges")]
        void SaveChanges();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="https://github.com/hbulens/Exam70487/ICustomerService/SaveChanges")]
        System.Threading.Tasks.Task SaveChangesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : hbulens.Exam70487.Wcf.Client.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<hbulens.Exam70487.Wcf.Client.CustomerService.ICustomerService>, hbulens.Exam70487.Wcf.Client.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public hbulens.Exam70487.Common.Customer[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<hbulens.Exam70487.Common.Customer[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public bool Add(hbulens.Exam70487.Common.Customer customer) {
            return base.Channel.Add(customer);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(hbulens.Exam70487.Common.Customer customer) {
            return base.Channel.AddAsync(customer);
        }
        
        public void SaveChanges() {
            base.Channel.SaveChanges();
        }
        
        public System.Threading.Tasks.Task SaveChangesAsync() {
            return base.Channel.SaveChangesAsync();
        }
    }
}
